services:
  db:
    image: postgres:16.1
    container_name: pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: inline
    ports:
      - "5433:5432"      # ← хост:контейнер
    volumes:
      - ./data/postgres:/var/lib/postgresql/data